#!/bin/sh
# Use this script to re-create configure. Requires the following auto-tools,
# autoconf        >= 2.59
# automake        >= 1.9
# libtool         >= 1.4
if test `which libtoolize`
then
        libtoolize --force
fi
aclocal -I ./config \
&& autoheader \
&& automake --foreign --add-missing --copy \
&& autoconf

