#!/bin/sh

cd `dirname $0`
if test -n $MYFLEX; then 
        FLEX=$MYFLEX
else
        FLEX=flex
fi
if test -n $MYCC; then
        CC=$MYCC
else
        CC=gcc
fi
$FLEX filterh.l || exit 1
$CC -c lex.yy.c || exit 1
$CC lex.yy.o -lfl -o ../bin/filterh || exit 1
rm -f lex.yy.*
exit 0